config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#home'

  devise_for  :users,
              path: '',
              path_names: {sign_in: 'login', 
                          sign_out: 'logout', 
                          edit: 'profile', 
                          sign_up: 'registration'}

  resources :users, only: [:show]
  resources :rooms, except: [:edit] do
    member do 
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'amenities'
      get 'location'
      get 'preload'
      get 'preview'
    end
    resources :roomphotos, only: [:create, :destroy]
    resources :reservations, only:[:create]
  end

  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews, only: [:create, :destroy]

  get '/mytrips' => 'reservations#mytrips'
  get '/myreservations' => 'reservations#myreservations'
  get 'search' => 'pages#search'

end

app/models/roomphoto.rb
class Roomphoto < ApplicationRecord
  belongs_to :room

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/roomphotos_controller.rb
class RoomphotosController < ApplicationController
  def create
    @room = Room.find(params[:room_id])

    if params[:images]
      params[:images].each do |img|
        @room.roomphotos.create(image: img)
      end
      redirect_back(fallback_location: request.referer, notice: "Saved...")
    end
    @roomphotos = @room.roomphotos

  end

  def destroy
    @photo = Roomphoto.find(params[:id])
    @room   = @photo.room

    @photo.destroy
    @photos = Roomphoto.where(room_id: @room.id)

    respond_to :js
  end
end

app/views/roomphotos/_photos_list.html.erb
<% if @photos.count > 0 %>
  <br>
  <div class="row">
    <div class="card-columns">
      <% @photos.each do |photo| %>
        <div class="card w-30">
          <%= image_tag photo.image.url(:medium), class: "card-img-top img-fluid rounded" %>
          <div class="card-body">
            <span class="pull-right">
              <%= link_to room_roomphoto_path(photo.room_id, photo), method: 'delete', remote: true, data: {confirm: "Are you sure?"} do %>
                <i class="fa fa-trash" aria-hidden="true"></i>
              <% end %>
            </span>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/roomphotos/destroy.js.erb
$("#roomphotos").html("<%= j render 'photos_list' %>");
<% if @room.roomphotos.blank? %>
  $("#roomphoto_check").hide();
<% end %>

<% if !@room.active && !@room.price.blank? && !@room.listing_name.blank? && !@room.roomphotos.blank? && !@room.address.blank? %>
  $("#publish_button").attr("disabled", false)
<% else %>
  $("#publish_button").attr("disabled", true)
<% end %>