config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#home'

  devise_for  :users,
              path: '',
              path_names: {sign_in: 'login', 
                          sign_out: 'logout', 
                          edit: 'profile', 
                          sign_up: 'registration'}

  resources :users, only: [:show]
  resources :rooms, except: [:edit] do
    member do 
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'amenities'
      get 'location'
      get 'preload'
      get 'preview'
    end
    resources :roomphotos, only: [:create, :destroy]
    resources :reservations, only:[:create]
  end

  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews, only: [:create, :destroy]

  get '/mytrips' => 'reservations#mytrips'
  get '/myreservations' => 'reservations#myreservations'
  get 'search' => 'pages#search'

end

app/views/shared/_devisemessage.html.erb
<% unless resource.errors.empty? %>
  <script type="text/javascript">
    <% resource.errors.full_messages.each do |v| %>
      toastr['error']('<%= v %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |k,v| %>
      <% type=k.to_s.gsub('alert', 'error').gsub('notice', 'success') %>
      toastr['<%= type %>']('<%= v %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_topbar.html.erb
<nav class="navbar navbar-expand-md navbar-light sticky-top bg-light">
  <div class="container">
    <%= link_to "Airoom", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <%= form_tag search_path, class: "form-inline mr-auto my-2 my-lg-0", method: :get do %>
        <div class="form-group">
          <%= text_field_tag :search, params[:search], placeholder: "Anywhere", class: "form-control" %>
        </div>
      <% end %>
      <ul class="navbar-nav navbar-right">
        <li class="nav-item active my-2">
          <div class="btn btn-info btn-nav">
            <% if (!user_signed_in?) %>
              <%= link_to "Become a Host", new_user_registration_path, class: "nav-link", style: "color: white;" %>
            <% else %>
              <%= link_to "Add a Room", new_room_path, class: "nav-link", style: "color: white;" %>
            <% end %>
          </div>
        </li>
        <% if (!user_signed_in?) %>
          <li class="nav-item p-0 my-1">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item p-0 my-1">
            <%= link_to "Log In", new_user_session_path, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item dropdown p-0 my-1">
            <a class="nav-link dropdown-toggle" href="" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag avatar_url(current_user), class: "rounded-circle avatar_small mr-1" %>
              <%= current_user.fullname %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <%= link_to "Manage Listing", rooms_path, class: "dropdown-item" %>
              <%= link_to "List Your Space", new_room_path, class: "dropdown-item" %>
              <%= link_to "Your Reservations", myreservations_path, class: "dropdown-item" %>
              <%= link_to "Your Trips", mytrips_path, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to "Edit", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>