config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#home'

  devise_for  :users,
              path: '',
              path_names: {sign_in: 'login', 
                          sign_out: 'logout', 
                          edit: 'profile', 
                          sign_up: 'registration'}

  resources :users, only: [:show]
  resources :rooms, except: [:edit] do
    member do 
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'amenities'
      get 'location'
      get 'preload'
      get 'preview'
    end
    resources :roomphotos, only: [:create, :destroy]
    resources :reservations, only:[:create]
  end

  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews, only: [:create, :destroy]

  get '/mytrips' => 'reservations#mytrips'
  get '/myreservations' => 'reservations#myreservations'
  get 'search' => 'pages#search'

end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/concerns/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!

  def create
    room = Room.find(params[:room_id])
    if current_user == room.user
      flash[:alert] = "You cannot book your own poperty"
    else
      start_date = Date.parse(reservation_params[:start_date])
      end_date = Date.parse(reservation_params[:end_date])
      days = end_date - start_date + 1

      @reservation = current_user.reservations.build(reservation_params)
      @reservation.room = room
      @reservation.price = room.price
      @reservation.total = room.price * days
      @reservation.save

      flash[:notice] = "Booked Successfully"
    end
      redirect_to room
  end

    private
      def reservation_params
        params.require(:reservation).permit(:start_date, :end_date)
      end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!

  def create
    room = Room.find(params[:room_id])
    if current_user == room.user
      flash[:alert] = "You cannot book your own poperty"
    else
      start_date = Date.parse(reservation_params[:start_date])
      end_date = Date.parse(reservation_params[:end_date])
      days = end_date - start_date

      @reservation = current_user.reservations.build(reservation_params)
      @reservation.room = room
      @reservation.price = room.price
      @reservation.total = room.price * days
      @reservation.save

      flash[:notice] = "Booked Successfully"
    end
      redirect_to room
  end

  def mytrips
    @trips = current_user.reservations.order(start_date: :asc)
  end

  def myreservations
    @rooms = current_user.rooms
  end

    private
      def reservation_params
        params.require(:reservation).permit(:start_date, :end_date)
      end

end

app/views/reservations/_form.html.erb
<div class="card">
  <div class="card-header">
    <span><i class="fa fa-bolt" style="color:#ffb400"></i> $<%= @room.price %></span>
    <span class="pull-right">Per Night</span>
  </div>
  <div class="card-body">
    <%= form_for([@room, @room.reservations.new]) do |f| %>
    <div class="row">
      <div class="col-md-6">
      <label>Check In</label>
        <%= f.text_field :start_date, readonly:true, placeholder: "Start Date", class: "form-control datepicker" %>
      </div>
      <div class="col-md-6">
        <label>Check Out</label>
        <%= f.text_field :end_date, readonly:true, disabled:true, placeholder: "End Date", class: "form-control datepicker" %>
      </div>
    </div>

    <p class="text-center message-alert"><span id="message"></span></p>
    <div id="preview" style="display: none;">
      <table class="reservation-table">
        <tbody>
          <tr>
            <td>Price</td>
            <td class="text-right">$<%= @room.price %></td>
          </tr>
          <tr>
            <td>Night(s)</td>
            <td class="text-right">x <span id="reservation_nights"></span></td>
          </tr>
          <tr>
            <td class="total">Total</td>
            <td class="text-right">$ <span id="reservation_total"></td>
          </tr>
        </tbody>
      </table>
    </div>
    
    <br>
    <%= f.submit "Book Now", id: "btn_book", class: "btn btn-primary btn-block", disabled:true %>
    <% end %>
  </div>
</div>

<script type="text/javascript">

  function checkDate(date) {
    dmy = date.getDate() + "-" + (date.getMonth()  + 1) + "-" + date.getFullYear();
    // console.log(dmy);
    // console.log(date);
    // console.log([$.inArray(dmy, unavailbleDates) == -1 ]);
    return [$.inArray(dmy, unavailbleDates) == -1 ]
  }

  $(function(){

    unavailbleDates = [];

    $.ajax({
      url: '<%= preload_room_path(@room) %>',
      dataType: 'json',
      success: function(data) {
        $.each(data, function(arrID, arrValue){
          
            console.log(arrValue);
            for(var d = new Date(arrValue.start_date); d <= new Date(arrValue.end_date); d.setDate(d.getDate() + 1)){
              unavailbleDates.push($.datepicker.formatDate('d-m-yy', d))
            }
        });

        $('#reservation_start_date').datepicker({
          dateFormat: 'dd-mm-yy',
          minDate: 0,
          maxDate: '2m',
          beforeShowDay: checkDate,
          onSelect: function(selected){
            $('#reservation_end_date').attr("disabled", false);
            $('#reservation_end_date').datepicker("option", "minDate", selected);
            var start_date = $('#reservation_start_date').datepicker('getDate');
            var end_date = $('#reservation_end_date').datepicker('getDate');
            var nights = (end_date-start_date)/1000/60/60/24;
            var total = nights * <%= @room.price %>;
            var input = {
              'start_date': start_date,
              'end_date': end_date
            };

            $.ajax({
              url: '<%= preview_room_path(@room) %>',
              data: input,
              success: function(data){
                if(data.conflict  || nights<1) {
                  $('#message').text("These days are not available");
                  $('#preview').hide();
                  $('#btn_book').attr('disabled', true)
                }else{
                  $('#message').text("");
                  $('#preview').show();
                  $('#btn_book').attr('disabled', false);
                  
                  $('#reservation_nights').text(nights);
                  $('#reservation_total').text(total);
                }
              }
            }) //ajax
          } //onselect
        });
        $('#reservation_end_date').datepicker({
          dateFormat: 'dd-mm-yy',
          minDate: 0,
          maxDate: '2m',
          beforeShowDay: checkDate,
          onSelect: function(selected){
            $('#reservation_start_date').datepicker("option", "maxDate", selected);
            var start_date = $('#reservation_start_date').datepicker('getDate');
            var end_date = $('#reservation_end_date').datepicker('getDate');
            var nights = (end_date-start_date)/1000/60/60/24;
            var total = nights * <%= @room.price %>;
            var input = {
              'start_date': start_date,
              'end_date': end_date
            };

            $.ajax({
              url: '<%= preview_room_path(@room) %>',
              data: input,
              success: function(data){
                if(data.conflict || nights<1) {
                  $('#message').text("These days are not available");
                  $('#preview').hide();
                  $('#btn_book').attr('disabled', true)
                }else{
                  $('#message').text("");
                  $('#preview').show();
                  $('#btn_book').attr('disabled', false);
                  
                  $('#reservation_nights').text(nights);
                  $('#reservation_total').text(total);
                }
              },
              error: function(XMLHttpRequest, textStatus, errorThrown) {
                alert(textStatus);
              }
            })

          }
        })

      },
      error: function(XMLHttpRequest, textStatus, errorThrown) {
        // alert(XMLHttpRequest.status);
        // alert(XMLHttpRequest.readyState);
        // alert(textStatus);
      }
    });
    
  })
</script>

app/views/reservations/myreservations.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="list-group">
      <%= link_to "Your Listings", rooms_path, class: "list-group-item list-group-item-action" %>
      <%= link_to "Your Reservations", myreservations_path, class: "list-group-item list-group-item-action active" %>
      <%= link_to "Your Trips", mytrips_path, class: "list-group-item list-group-item-action" %>
    </ul>
  </div>

  <div class="col-md-9">
    <div class="card">
      <div class="card-header">
        Your Reservations
      </div>
      <div class="card-body">
        <div class="container">
          <% @rooms.each do |room| %>
            <% room.reservations.each do |reservation| %>
              <div class="row align-items-center">
                <div class="col-md-2">
                  <%=  reservation.start_date.strftime('%v') %>
                </div>
                <div class="col-md-2" style="height:80px;overflow:hidden;">
                  
                    <%= image_tag reservation.room.use_first_photo(:medium), class: "img-fluid mx-auto d-block img-middle" %>
                  
                </div>
                <div class="col-md-6">
                  <div class="row mb-2">
                    <h5><%= link_to reservation.room.listing_name, room_path(reservation.room) %></h5>
                  </div>
                  <div class="row">
                    <span>
                      <%= image_tag avatar_url(reservation.user), class: "avatar_small rounded-circle" %>
                      <%= link_to user_path(reservation.user) do %>
                        <%= reservation.user.fullname %>
                      <%end%>
                    </span>
                  </div>
                </div>
                <div class="col-md-2 text-right">
                  <%= render partial: "reviews/host_review_form", locals: {reservation: reservation} %>
                </div>
              </div>
              <hr/>
            <% end %>
          <% end %>
            
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reservations/mytrips.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="list-group">
      <%= link_to "Your Listings", rooms_path, class: "list-group-item list-group-item-action" %>
      <%= link_to "Your Reservations", myreservations_path, class: "list-group-item list-group-item-action" %>
      <%= link_to "Your Trips", mytrips_path, class: "list-group-item list-group-item-action active" %>
    </ul>
  </div>

  <div class="col-md-9">
    <div class="card">
      <div class="card-header">
        Your Trips
      </div>
      <div class="card-body">
        <div class="container">
          <% @trips.each do |trip| %>
            <div class="row align-items-center mb-4">
              <div class="col-md-2">
                <%=  trip.start_date.strftime('%v') %>
              </div>
              <div class="col-md-2" style="height:80px;overflow:hidden;">
                <%= image_tag trip.room.use_first_photo(:medium), class: "img-fluid mx-auto d-block img-middle" %>
              </div>
              <div class="col-md-6">
                  <div class="row mb-2">
                    <h5><%= link_to trip.room.listing_name, room_path(trip.room) %></h5>
                  </div>
                  <div class="row">
                    <span>
                      <%= image_tag avatar_url(trip.user), class: "avatar_small rounded-circle" %>
                      <%= link_to user_path(trip.user) do %>
                        <%= trip.user.fullname %>
                      <%end%>
                    </span>
                  </div>
                </div>
              <div class="col-md-2 text-right">
                <%= render partial: "reviews/guest_review_form", locals: {reservation: trip} %>
              </div>
            </div>
            <hr/>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>