config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#home'

  devise_for  :users,
              path: '',
              path_names: {sign_in: 'login', 
                          sign_out: 'logout', 
                          edit: 'profile', 
                          sign_up: 'registration'}

  resources :users, only: [:show]
  resources :rooms, except: [:edit] do
    member do 
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'amenities'
      get 'location'
      get 'preload'
      get 'preview'
    end
    resources :roomphotos, only: [:create, :destroy]
    resources :reservations, only:[:create]
  end

  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews, only: [:create, :destroy]

  get '/mytrips' => 'reservations#mytrips'
  get '/myreservations' => 'reservations#myreservations'
  get 'search' => 'pages#search'

end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :roomphotos
  has_many :reservations
  has_many :guest_reviews

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  validates :home_type,  presence: true
  validates :room_type,  presence: true
  validates :accommodate, presence: true
  validates :bed_room ,  presence: true
  validates :bath_room,  presence: true

  def use_first_photo(size = nil)
    if self.roomphotos.length > 0
      pic = self.roomphotos[0].image.url(size)
    else
      pic = "photo_blank.png"
    end
    pic
  end

  def average_rating
    guest_reviews.count == 0 ? 0 : guest_reviews.average(:star).round(2).to_i
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, except: [:index, :new, :create]
  before_action :authenticate_user!, except: [:show]
  before_action :is_owner?, only: [:update, :listing, :pricing, :description, :photo_upload, :amenities, :location]

  # for everyone
  def show
    @roomphotos = @room.roomphotos
    @guest_reviews = @room.guest_reviews
  end

  # for current_user
  def index
    @rooms = current_user.rooms
  end

  def new
    @room = current_user.rooms.build
  end

  def create
    @room = current_user.rooms.build(room_params)
    if @room.save
      flash[:notice] = "Saved..."
      redirect_to listing_room_path(@room)
    else
      flash[:alert] = "Something went wrong..."
      render :new
    end
  end

  def update
    if @room.update(room_params)
      flash[:notice] = "Saved..."
    else
      flash[:alert] = "Something went wrong..."
    end
    redirect_back(fallback_location: request.referer)
  end

  def listing
  end

  def pricing
  end

  def description
  end

  def photo_upload
    @photos = @room.roomphotos
  end

  def amenities
  end

  def location
  end

  # for reservation ajax
  def preload
    today = Date.today
    reservations = @room.reservations.where("start_date >= ? OR end_date >= ?", today, today)

    render json: reservations
  end

  def preview
    start_date = Date.parse(params[:start_date])
    end_date = Date.parse(params[:end_date])
    output = {
      conflict: is_conflict(start_date, end_date, @room)
    }

    render json: output
  end

  private
    def is_conflict(start_date, end_date, room)
      check = room.reservations.where("? < start_date AND end_date < ?", start_date, end_date)
      check.size > 0 ? true : false
    end

    def set_room
      @room = Room.find(params[:id])
    end

    def is_owner?
      redirect_to root_path, alert: "You don't have permission" unless current_user.id == @room.user_id
    end

    def room_params
      params.require(:room).permit(:home_type,
                                  :room_type,
                                  :accommodate,
                                  :bed_room,
                                  :bath_room,
                                  :listing_name,
                                  :summary,
                                  :address,
                                  :is_tv,
                                  :is_kitchen,
                                  :is_air,
                                  :is_heating,
                                  :is_internet,
                                  :price,
                                  :active)
    end
end

app/helpers/room_helper.rb
module RoomHelper
end

app/views/rooms/_room_footer.html.erb
    </div>
  </div>
</div>

app/views/rooms/_room_header.html.erb
<div class="row">
  <%= render "room_menu" %>
  <div class="col-md-9">
    <div class="card">

app/views/rooms/_room_menu.html.erb
<div class="col-md-3">
  <ul class="list-group">
    <div class="list-group-item list-group-item-action">
      <%= link_to 'Listing', listing_room_path %>
      <span class="pull-right color-info"><i class="fa fa-check"></i></span>
    </div>
    <div class="list-group-item list-group-item-action">
      <%= link_to 'Pricing', pricing_room_path %>
      <% if !@room.price.blank? %>
        <span class="pull-right color-info"><i class="fa fa-check"></i></span>
      <% end %>
    </div>
    <div class="list-group-item list-group-item-action">
      <%= link_to 'Description', description_room_path %>
      <% if !@room.listing_name.blank? %>
        <span class="pull-right color-info"><i class="fa fa-check"></i></span>
      <% end %>
    </div>
    <div class="list-group-item list-group-item-action">
      <%= link_to 'Photo Uplad', photo_upload_room_path %>
      <% if !@room.roomphotos.blank? %>
        <span id="roomphoto_check" class="pull-right color-info"><i class="fa fa-check"></i></span>
      <% end %>
    </div>
    <div class="list-group-item list-group-item-action">
      <%= link_to 'Amenities', amenities_room_path %>
      <span class="pull-right color-info"><i class="fa fa-check"></i></span>
    </div>
    <div class="list-group-item list-group-item-action">
      <%= link_to 'Location', location_room_path %>
      <% if !@room.address.blank? %>
        <span class="pull-right color-info"><i class="fa fa-check"></i></span>
      <% end %>
    </div>    
  </ul>
  <hr>
  <% is_ready = !@room.active && !@room.price.blank? && !@room.listing_name.blank? && !@room.roomphotos.blank? && !@room.address.blank? %>
  <%= form_for @room do |f| %>
    <%= f.hidden_field :active, value: true %>
    <%= f.submit "Publish", id: "publish_button", class: "btn btn-primary btn-block", disabled: !is_ready %>
  <% end %>
  <br>
  <%= if @room.active
    form_for @room do |f| %>
    <%= f.hidden_field :active, value: false %>
    <%= f.submit "Don't Publish", id: "no_publish_button", class: "btn btn-scendary btn-block" %>
  <% end 
  end %>
</div>

app/views/rooms/_rooms_list.html.erb
<% rooms.each do |room| %>
  <div class="col-md-4">
    <div class="card">
        <%= image_tag room.use_first_photo(:medium), class: "card-img-top img-fluid " %>
        <div class="card-body" style="font-size: smaller;">
          <div style="font-size: larger"><%= link_to room.listing_name, room_path(room) %></div>
          <div>$<%= room.price %> - <%= room.home_type%> - <%= pluralize(room.bed_room, "bed") %></div>
          <div id="star_<%= room.id %>"></div> <%= pluralize(room.average_rating, "review") %>
        </div>
    </div>
  </div>

    <script type="text/javascript">
      $('#star_<%= room.id %>').raty({
        path: "/img",
        readOnly: true,
        score: <%= room.average_rating %>
      })
    </script>

<% end %>

app/views/rooms/amenities.html.erb
<%= render 'room_header' %>
  <div class="card-header">
    Amentities
  </div>
  <div class="card-body">
    <div class="container">
      <%= form_for @room do |f|%>
        
        <div class="row form-group">
          <div class="col-md-4">
            <%= f.check_box :is_tv %> TV
          </div>
          <div class="col-md-4">
            <%= f.check_box :is_kitchen %> Kitchen
          </div>
          <div class="col-md-4">
            <%= f.check_box :is_internet %> Internet
          </div>
        </div>

        <div class="row form-group">
          <div class="col-md-4">
            <%= f.check_box :is_heating %> Heating
          </div>
          <div class="col-md-4">
            <%= f.check_box :is_air %> Air Conditioning
          </div>
        </div>

        <div class="text-center">
          <%= f.submit "Save", class: "btn btn-info w-50" %>
        </div>

      <% end %>
    </div>
  </div>
<%= render 'room_footer' %>

app/views/rooms/create.html.erb
<h1>Room#create</h1>
<p>Find me in app/views/room/create.html.erb</p>

app/views/rooms/description.html.erb
<%= render 'room_header' %>
  <div class="card-header">
    Description
  </div>
  <div class="card-body">
    <div class="container">
      <%= form_for @room do |f|%>

        <div class="row">
          <div class="form-group w-100">
            <label>Listing name</label>
            <%= f.text_field :listing_name, placeholder: "What is your listing name?", class: "form-control" %>
          </div>
        </div>

        <div class="row">
          <div class="form-group w-100">
            <label>Summary</label>
            <%= f.text_area :summary, rows: 5, placeholder: "Summary of your house", class: "form-control" %>
          </div>
        </div>

        <div class="text-center">
          <%= f.submit "Save", class: "btn btn-info w-50" %>
        </div>

      <% end %>
    </div>
  </div>
<%= render 'room_footer' %>

app/views/rooms/index.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="list-group">
      <%= link_to "Your Listings", rooms_path, class: "list-group-item list-group-item-action active" %>
      <%= link_to "Your Reservations", myreservations_path, class: "list-group-item list-group-item-action" %>
      <%= link_to "Your Trips", mytrips_path, class: "list-group-item list-group-item-action" %>
    </ul>
  </div>

  <div class="col-md-9">
    <div class="card">
      <div class="card-header">
        Your Rooms
      </div>
      <div class="card-body">
        <div class="container">
          <% @rooms.each do |room| %>
            <div class="row align-items-center mb-4">
              <div class="col-md-3" style="height:100px;overflow:hidden;">
                <%= image_tag room.use_first_photo(:medium), class: "img-fluid mx-auto d-block img-middle" %>
              </div>
              <div class="col-md-6">
                <h4><%= room.listing_name %></h4>
              </div>
              <div class="col-md-3">
                <%= link_to "Update", listing_room_path(room), class: "btn btn-info btn-block" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/listing.html.erb
<%= render 'room_header' %>
  <div class="card-header">
    Creat your beautiful place
  </div>
  <div class="card-body">
    <div class="container">
      <%= form_for @room do |f|%>
        <div class="row form-group">

          <div class="col-md-4 select">
            <label>Home Type</label>
            <%= f.select :home_type, [["Apartment","Apartment"], ["House", "House"], ["Bed & Breakfast", "Bed & Breakfast"]],
                         id: "home_type", prompt: "Select...", class: "form_control" %>
          </div>

          <div class="col-md-4 select">
            <label>Room Type</label>
            <%= f.select :room_type, [["Entire","Entire"], ["Private", "Private"], ["Shared", "Shared"]],
                         id: "room_type", prompt: "Select...", class: "form_control" %>
          </div>

          <div class="col-md-4 select">
            <label>Accommodate</label>
            <%= f.select :accommodate, [["1",1], ["2", 2], ["3", 3], ["4", 4]],
                         id: "accommodate", prompt: "Select...", class: "form_control" %>
          </div>

          <div class="col-md-4 select">
            <label>Bedrooms</label>
            <%= f.select :bed_room, [["1",1], ["2", 2], ["3", 3], ["4", 4]],
                         id: "bed_room", prompt: "Select...", class: "form_control" %>
          </div>

          <div class="col-md-4 select">
            <label>Bathrooms</label>
            <%= f.select :bath_room, [["1",1], ["2", 2], ["3", 3], ["4", 4]],
                         id: "bath_room", prompt: "Select...", class: "form_control" %>
          </div>

        </div>

        <div class="text-center">
          <%= f.submit "Save", class: "btn btn-info w-50" %>
        </div>

      <% end %>
    </div>
  </div>
  
<%= render 'room_footer' %>

app/views/rooms/new.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        Creat your beautiful place
      </div>
      <div class="card-body">
        <div class="container">
          <%= form_for @room do |f|%>
            <div class="row form-group">

              <div class="col-md-4 select">
                <label>Home Type</label>
                <%= f.select :home_type, [["Apartment","Apartment"], ["House", "House"], ["Bed & Breakfast", "Bed & Breakfast"]],
                             id: "home_type", prompt: "Select...", class: "form_control" %>
              </div>

              <div class="col-md-4 select">
                <label>Room Type</label>
                <%= f.select :room_type, [["Entire","Entire"], ["Private", "Private"], ["Shared", "Shared"]],
                             id: "room_type", prompt: "Select...", class: "form_control" %>
              </div>

              <div class="col-md-4 select">
                <label>Accommodate</label>
                <%= f.select :accommodate, [["1",1], ["2", 2], ["3", 3], ["4", 4]],
                             id: "accommodate", prompt: "Select...", class: "form_control" %>
              </div>

              <div class="col-md-4 select">
                <label>Bedrooms</label>
                <%= f.select :bed_room, [["1",1], ["2", 2], ["3", 3], ["4", 4]],
                             id: "bed_room", prompt: "Select...", class: "form_control" %>
              </div>

              <div class="col-md-4 select">
                <label>Bathrooms</label>
                <%= f.select :bath_room, [["1",1], ["2", 2], ["3", 3], ["4", 4]],
                             id: "bath_room", prompt: "Select...", class: "form_control" %>
              </div>

            </div>

            <div class="text-center">
              <%= f.submit "Creat My Room", class: "btn btn-primary w-50" %>
            </div>

          <% end %> 
        </div>
      </div>
    </div>
  </div>
</div>

  

app/views/rooms/photo_upload.html.erb
<%= render 'room_header' %>
  <div class="card-header">
    Photos
  </div>
  <div class="card-body">
    <div class="container">
      <%= form_for @room, url: room_roomphotos_path(@room), method: 'post', html: {multipart: true} do |f|%>

        <div class="row text-center">
          <div class="col form-group">
            <span class="btn btn-light btn-file">
              <i class="fa fa-cloud-upload" aria-hidden="true"></i> Select Photos
              <%= file_field_tag "images[]", type: :file, multiple: true %>
            </span>
          </div>
        </div>

        <div class="text-center">
          <%= f.submit "Add Photos", class: "btn btn-info" %>
        </div>

        <div id="roomphotos">
          <%= render 'roomphotos/photos_list' %>
        </div>
      <% end %>
    </div>
  </div>
<%= render 'room_footer' %>

app/views/rooms/pricing.html.erb
<%= render 'room_header' %>
  <div class="card-header">
    Pricing
  </div>
  <div class="card-body">
    <div class="container">
      <%= form_for @room do |f|%>

        <div class="row">
          <div class="form-group w-100">
            <label>Price</label>
            <%= f.text_field :price, placeholder:"eg: $100", class: "form-control" %>
          </div>
        </div>

        <div class="text-center">
          <%= f.submit "Save", class: "btn btn-info w-50" %>
        </div>

      <% end %>
    </div>
  </div>
<%= render 'room_footer' %>

app/views/rooms/show.html.erb
<!-- Imgae -->
<div class="row">
  <div class="col-md-12" style="height:400px;overflow:hidden;">
    <%= image_tag @room.use_first_photo, class: "w-100 img-fluid mx-auto d-block img-middle" %>
  </div>
</div>

<div class="row mt-4">

  <!-- left panel -->
  <div class="col-md-8">

    <!-- listing_name -->
    <div class="row">
      <div class="col-md-9">
        <h2><%= @room.listing_name %></h2>
        <%= @room.address %>
      </div>
      <div class="col-md-3 text-center">
        <div class="text-center">
          <%= image_tag avatar_url(@room.user), class: "rounded-circle avatar_middle" %>
        </div>
        <div class="text-center">
          <%= @room.user.fullname %>
        </div>
      </div>
    </div>
    <hr>

    <!-- room info -->
    <div class="row ">
      <div class="row text-center w-100">
        <div class="col-md-3">
          <i class="fa fa-home fa-2x"></i>
        </div>
        <div class="col-md-3">
          <i class="fa fa-user-circle-o fa-2x"></i>
        </div>
        <div class="col-md-3">
          <i class="fa fa-bed fa-2x"></i>
        </div>
        <div class="col-md-3">
          <i class="fa fa-bath fa-2x"></i>
        </div>
      </div>
      <div class="row text-center w-100">
        <div class="col-md-3"><%= @room.home_type %></div>
        <div class="col-md-3"><%= pluralize(@room.accommodate, "Guest") %></div>
        <div class="col-md-3"><%= pluralize(@room.bed_room, "Bedroom") %></div>
        <div class="col-md-3"><%= pluralize(@room.bath_room, "Bathroom") %></div>
      </div>
    </div>
    <hr>

    <!-- description -->
    <div class="row">
      <div class="col-md-12">
        <h4>About this Listing</h4>
        <p><%= @room.summary %></p>
      </div>
    </div>
    <hr>

    <!-- amenities -->
    <div class="row">
      <div class="col-md-12">
        <h4>Amentities</h4>
        <div class="row amenities">
          <div class="col-md-6">
            <ul>
              <li class="<%= 'text-line-through' if !@room.is_tv %>">TV</li>
              <li class="<%= 'text-line-through' if !@room.is_kitchen %>">Kitchen</li>
              <li class="<%= 'text-line-through' if !@room.is_internet %>">Internet</li>
            </ul>
          </div>
          <div class="col-md-6">
            <ul>
              <li class="<%= 'text-line-through' if !@room.is_heating %>">Heating</li>
              <li class="<%= 'text-line-through' if !@room.is_air %>">Air Conditioning</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <hr>

    <!-- photos -->
    <div class="row">

      <% if @roomphotos.length > 0 %>
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" >
          <ol class="carousel-indicators">
            <% @roomphotos.each do |photo| %>
              <li data-target="#carouselExampleIndicators" data-slide-to="<%= photo.id %>"></li>
            <% end %>
          </ol>
          <div class="carousel-inner">
            <% @roomphotos.each do |photo| %>
              <div class="carousel-item <%= 'active' if photo.id == @roomphotos[0].id %>">
                <img class="w-100 d-block img-middle" src="<%= photo.image.url %>">
              </div>
            <% end %>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      <% end %>

    </div>
    <hr>

    <!-- comment -->
    <div class="row">
      <div class="col-md-12">
        <h4>
          <%= pluralize(@guest_reviews.count, "Review") %>
          <span id="average_rating"></span>
        </h4>
        <div class="container">
          <div><%= render "reviews/guest_list" %></div>
        </div>
      </div>
    </div>
    <br>
    <hr>

    <!-- maps -->
    <div class="row">
      <div id="map" style="width:100%;height:400px"></div>
      <script type="text/javascript">
        function initMap(){
          var location = {lat: <%= @room.latitude %>, lng: <%= @room.longitude %>};
          var map = new google.maps.Map(document.getElementById("map"), {
            center: location,
            zoom: 14
          });
          var marker = new google.maps.Marker({
            position: location,
            map: map
          });
          var infoWindow = new google.maps.InfoWindow({
            content: '<div id="content"><%= image_tag @room.use_first_photo(:thumb) %></div>'
          });
          infoWindow.open(map, marker)
        }
        // google.maps.event.addDomListener(window, 'load', initMap)
      </script>
      <script async defer type="text/javascript" src="//maps.googleapis.com/maps/api/js?key=AIzaSyBTHe6Ilnvf5pN1Zv8s1I2PLLBFiex1BKs&callback=initMap"></script>
    </div>
    <hr>

    <!-- nearby -->
    <div class="row">
      <div class="col-md-12">
        <h4>Near By</h4>
      <div class="row">
      <% if @room.nearbys(10) %>
        <%= render partial: "rooms/rooms_list", locals: {rooms:  @room.nearbys(10).max(6)} %>
      <% end %>
       </div>
       </div>
    </div>

  </div>

  <!-- right panel -->
  <div class="col-md-4">
    <div class="row">
      <%= render "reservations/form" %>  
    </div>
  </div>

</div>

<script type="text/javascript">
  $('#average_rating').raty({
    path: "/img",
    readOnly: true,
    scoreName: 'host_review[star]',
    score: <%= @room.average_rating %>
  })
</script>

app/views/rooms/update.html.erb
<h1>Room#update</h1>
<p>Find me in app/views/room/update.html.erb</p>